variables:
  MAVEN_OPTS: '-Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true'
  MAVEN_CLI_OPTS: '--batch-mode --errors --fail-at-end --show-version -s ci_settings.xml'
  SKIP_TESTS: '-DskipTests=true -Djacoco.skip=true'
  CACHE_KEY: $CI_COMMIT_REF_SLUG
  TARGET_PLATFORM: 'linux/amd64'
  TAG_REGEX: '/^\d+\.\d+\.\d+$/'
  BUILD_TEST_STAGE: 'BUILD_TEST'
  CONTAINERIZE_STAGE: 'CONTAINERIZE'
  RETAG_STAGE: 'RETAG'
  DEPLOY_STAGE: 'DEPLOY'
  DEPLOY_SECRET:
    description: "Flag to decide whether secret(s) have been changed & needs deployment. Default is false, set to true if there is a change."
    value: "false"
  STAGE:
    description: 'Pipeline stages, BUILD_TEST, CONTAINERIZE, RETAG & DEPLOY. Select appropriately!'
    value: 'BUILD_TEST'
  PLATFORM_ENV:
    description: 'Platform environment, dev is default. For production use prod'
    value: 'dev'
  GCP_PROJECT_NUMBER:
    description: 'GCP project id, provide appropriate project id, default is set to dev instance'
    value: '968549395092'

cache:
  key: $CACHE_KEY
  paths:
    - .m2/repository/

stages:
  - build
  - test
  - containerize
  - retag
  - deploy

build:
  stage: build
  image: maven:3.8.7-eclipse-temurin-19
  script:
    - 'echo "Building BFF"'
    - 'mvn $MAVEN_CLI_OPTS package $SKIP_TESTS --also-make'
  artifacts:
    paths:
      - target/
    expire_in: 30 min
  rules:
    - if: '$STAGE == $BUILD_TEST_STAGE || $STAGE == $CONTAINERIZE_STAGE'
      when: always

test:
  stage: test
  image: maven:3.8.7-eclipse-temurin-19
  script:
    - 'echo Testing BFF'
    - 'mvn $MAVEN_CLI_OPTS surefire:test --also-make'
  rules:
    - if: '$STAGE == $BUILD_TEST_STAGE || $STAGE == $CONTAINERIZE_STAGE'
      when: always

containerize:
  stage: containerize
  image:
    name: gcr.io/kaniko-project/executor:v1.14.0-debug
    entrypoint: [ "" ]
  script:
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/docker/Dockerfile"
      --build-arg "TARGET_PLATFORM=${TARGET_PLATFORM}"
      --destination "${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}-dev"
  rules:
    - if: '$CI_PIPELINE_SOURCE == "web" && $CI_COMMIT_TAG && $CI_COMMIT_TAG =~ $TAG_REGEX && $STAGE == $CONTAINERIZE_STAGE'
      when: always

retag:
  stage: retag
  image:
    name: gcr.io/go-containerregistry/crane:debug
    entrypoint: [""]
  variables:
    GIT_STRATEGY: none
  script:
    - crane auth login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
    - crane cp "$CI_REGISTRY_IMAGE:$CI_COMMIT_TAG-dev" "$CI_REGISTRY_IMAGE:$CI_COMMIT_TAG-prod"
  rules:
    - if: '$CI_PIPELINE_SOURCE == "web" && $CI_COMMIT_TAG && $CI_COMMIT_TAG =~ $TAG_REGEX && $STAGE == $RETAG_STAGE'
      when: manual

deploy:
  stage: deploy
  image: alpine/k8s:1.32.0
  variables:
    K8S_CLUSTER_AGENT: gdp/ga4k:gcp-k8s-agent
    ENV_FILE: 'gcp-dev-env'
    NAMESPACE: 'intervene-dev'
  id_tokens:
    GCP_ID_TOKEN:
      # Keep same names/location in diff. envs.
      aud: https://iam.googleapis.com/projects/${GCP_PROJECT_NUMBER}/locations/global/workloadIdentityPools/${GCP_WORKLOAD_IDENTITY_FEDERATION_POOL_ID}/providers/${GCP_WORKLOAD_IDENTITY_FEDERATION_PROVIDER_ID}
  secrets:
    DATABASE_SECRET:
      gcp_secret_manager:
        name: projects/${GCP_PROJECT_NUMBER}/secrets/database-secret
      token: $GCP_ID_TOKEN
  before_script:
    - |
      if [[ "$PLATFORM_ENV" == "prod" ]]; then
        export NAMESPACE="intervene-prod"
        export ENV_FILE="gcp-prod-env"
        export K8S_CLUSTER_AGENT="gdp/ga4k:gcp-prod-k8s-agent"
      fi
  script:
    - 'echo Deploying to project: $GCP_PROJECT_NUMBER'
    - kubectl config get-contexts
    - kubectl config use-context $K8S_CLUSTER_AGENT
    - kubectl -n $NAMESPACE get pods
    - 'echo DEPLOY_SECRET value is set to $DEPLOY_SECRET'
    - if [[ "$DEPLOY_SECRET" == "true" ]]; then
        mv "$DATABASE_SECRET" "$DATABASE_SECRET.yaml";
        SECRET_FILES_PATH=$(dirname "$DATABASE_SECRET");
        kubectl -n "$NAMESPACE" apply -f "$SECRET_FILES_PATH"/;
      else
        echo "Skipping secret deployment.";
      fi
    - |
      helm upgrade --install backend-for-frontend "./deployments" -f "./deployments/values-${ENV_FILE}.yaml" \
      --namespace "$NAMESPACE" \
      --set image.tag="$CI_COMMIT_TAG"
  rules:
    - if: '$CI_PIPELINE_SOURCE == "web" && $CI_COMMIT_TAG && $CI_COMMIT_TAG =~ $TAG_REGEX && $STAGE == $DEPLOY_STAGE'
      when: manual
