#####################################################################################
# Application config
#####################################################################################
spring.application.name=backend-for-frontend-gateway
spring.webflux.base-path=/bff
spring.profiles.active=${ENV:dev}
#####################################################################################
# Metrics config
#####################################################################################
management.endpoints.web.exposure.include=health
