#####################################################################################
# Application Configuration
#####################################################################################
spring.application.name=backend-for-frontend-gateway
server.port=8090
spring.webflux.base-path=/bff
spring.profiles.active=${ENV:dev-env}
