#####################################################################################
# Application config
#####################################################################################
server.port=8090
#####################################################################################
# Spring Security OAuth2 Client Registration
#####################################################################################
spring.security.oauth2.client.registration.elixir.client-name=Login with the Elixir Identity Server
spring.security.oauth2.client.registration.elixir.client-id=18d2c177-41dd-40c6-8309-3c313601d5d7
spring.security.oauth2.client.registration.elixir.client-authentication-method=none
spring.security.oauth2.client.registration.elixir.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.elixir.redirect-uri=http://localhost:8090/bff/login/oauth2/code/{registrationId}
spring.security.oauth2.client.registration.elixir.scope[0]=openid
spring.security.oauth2.client.registration.elixir.scope[1]=profile
spring.security.oauth2.client.registration.elixir.scope[2]=email
spring.security.oauth2.client.registration.elixir.scope[3]=offline_access
spring.security.oauth2.client.provider.elixir.issuer-uri=https://login.elixir-czech.org/oidc/
spring.security.oauth2.client.provider.elixir.success-url=http://localhost:8090/bff/dev/ui/pgs-calculator
spring.security.oauth2.client.logout-uri=/logout
#####################################################################################
# R2DBC Config Details
#####################################################################################
spring.r2dbc.url=r2dbc:postgresql://localhost:5432/intervene?currentSchema=intervene-dev&ssl=true&sslMode=disable
spring.r2dbc.username=@datasource.intervene.username@
spring.r2dbc.password=@datasource.intervene.password@
#####################################################################################
# Spring Gateway Config
#####################################################################################
spring.cloud.gateway.default-filters[0]=DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin

spring.cloud.gateway.routes[0].id=file-handler
spring.cloud.gateway.routes[0].uri=http://localhost:8010
spring.cloud.gateway.routes[0].predicates=Path=${spring.webflux.base-path}/file-handler/**
spring.cloud.gateway.routes[0].filters[0]=StripBasePath=1
spring.cloud.gateway.routes[0].filters[1]=TokenRelay=

spring.cloud.gateway.routes[1].id=pipeline-manager
spring.cloud.gateway.routes[1].uri=http://localhost:8020
spring.cloud.gateway.routes[1].predicates=Path=${spring.webflux.base-path}/pipeline-manager/**
spring.cloud.gateway.routes[1].filters[0]=StripBasePath=1
spring.cloud.gateway.routes[1].filters[1]=TokenRelay=

spring.cloud.gateway.routes[2].id=user-manager
spring.cloud.gateway.routes[2].uri=http://localhost:8030
spring.cloud.gateway.routes[2].predicates=Path=${spring.webflux.base-path}/user-manager/**
spring.cloud.gateway.routes[2].filters[0]=StripBasePath=1
spring.cloud.gateway.routes[2].filters[1]=TokenRelay=

spring.cloud.gateway.routes[3].id=ui
spring.cloud.gateway.routes[3].uri=http://localhost:3000
spring.cloud.gateway.routes[3].predicates=Path=${spring.webflux.base-path}/dev/ui/**
#####################################################################################
# Redis Config
#####################################################################################
spring.redis.host=localhost
spring.redis.port=6379
spring.redis.client-type=lettuce
#####################################################################################
# Spring Session Config
#####################################################################################
spring.session.store-type=redis
spring.session.timeout=5h
spring.webflux.session.timeout=5h
#####################################################################################
# Log Config
#####################################################################################
logging.level.root=INFO
logging.level.uk.ac.ebi.gdp.intervene.igs4eu.bff=INFO
logging.level.org.springframework.security=INFO
logging.level.org.springframework.cloud=INFO
#####################################################################################
# Web Session Config
#####################################################################################
web-session.cookie.path=/
web-session.cookie.domain=localhost
web-session.cookie.http-only=true
web-session.cookie.same-site=Lax
web-session.cookie.secure=true
#####################################################################################
# Web Client Config
#####################################################################################
web-client.base-url=/bff/dev/ui
#####################################################################################
# BFF config
#####################################################################################
whitelist.uri=/dev/ui/**
