#####################################################################################
# Application config
#####################################################################################
server.port=8080
#####################################################################################
# Spring Security OAuth2 Client Registration
#####################################################################################
spring.security.oauth2.client.registration.elixir.client-name=Login with the Elixir Identity Server
spring.security.oauth2.client.registration.elixir.client-id=18d2c177-41dd-40c6-8309-3c313601d5d7
spring.security.oauth2.client.registration.elixir.client-authentication-method=none
spring.security.oauth2.client.registration.elixir.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.elixir.redirect-uri=https://gcp.geneticscores.org/bff/login/oauth2/code/{registrationId}
spring.security.oauth2.client.registration.elixir.scope[0]=openid
spring.security.oauth2.client.registration.elixir.scope[1]=profile
spring.security.oauth2.client.registration.elixir.scope[2]=email
spring.security.oauth2.client.registration.elixir.scope[3]=offline_access
spring.security.oauth2.client.provider.elixir.issuer-uri=https://login.elixir-czech.org/oidc/
spring.security.oauth2.client.provider.elixir.success-url=https://gcp.geneticscores.org/pgs-calculator
spring.security.oauth2.client.logout-uri=/logout
#####################################################################################
# R2DBC config
#####################################################################################
spring.r2dbc.url=r2dbc:postgresql://127.0.0.1:5432/intervene?currentSchema=intervene-dev&sslMode=disable
spring.r2dbc.username=${DB_USERNAME}
spring.r2dbc.password=${DB_PASSWORD}
#####################################################################################
# Spring Gateway config
#####################################################################################
spring.cloud.gateway.routes[0].id=file-handler
spring.cloud.gateway.routes[0].uri=http://file-handler.intervene-dev.svc.cluster.local:8080
spring.cloud.gateway.routes[0].predicates=Path=${spring.webflux.base-path}/file-handler/**
spring.cloud.gateway.routes[0].filters[0]=StripBasePath=1
spring.cloud.gateway.routes[0].filters[1]=TokenRelay=

spring.cloud.gateway.routes[1].id=pipeline-manager
spring.cloud.gateway.routes[1].uri=http://pipeline-manager.intervene-dev.svc.cluster.local:8080
spring.cloud.gateway.routes[1].predicates=Path=${spring.webflux.base-path}/pipeline-manager/**
spring.cloud.gateway.routes[1].filters[0]=StripBasePath=1
spring.cloud.gateway.routes[1].filters[1]=TokenRelay=

spring.cloud.gateway.routes[2].id=user-manager
spring.cloud.gateway.routes[2].uri=http://user-manager.intervene-dev.svc.cluster.local:8080
spring.cloud.gateway.routes[2].predicates=Path=${spring.webflux.base-path}/user-manager/**
spring.cloud.gateway.routes[2].filters[0]=StripBasePath=1
spring.cloud.gateway.routes[2].filters[1]=TokenRelay=

spring.cloud.gateway.routes[3].id=key-handler
spring.cloud.gateway.routes[3].uri=http://key-handler.intervene-dev.svc.cluster.local:8080
spring.cloud.gateway.routes[3].predicates=Path=${spring.webflux.base-path}/key-handler/**
spring.cloud.gateway.routes[3].filters[0]=StripBasePath=1
spring.cloud.gateway.routes[3].filters[1]=TokenRelay=
#####################################################################################
# Redis config
#####################################################################################
spring.redis.host=redis.intervene-dev.svc.cluster.local
spring.redis.port=6379
spring.redis.client-type=lettuce
#####################################################################################
# Spring Session config
#####################################################################################
spring.session.store-type=redis
spring.session.timeout=5h
spring.webflux.session.timeout=5h
#####################################################################################
# Log Config
#####################################################################################
logging.level.root=INFO
logging.level.uk.ac.ebi.gdp.intervene.igs4eu.bff=INFO
logging.level.org.springframework.security=INFO
logging.level.org.springframework.cloud=INFO
#####################################################################################
# Web Session config
#####################################################################################
web-session.cookie.path=/
web-session.cookie.domain=gcp.geneticscores.org
web-session.cookie.http-only=true
web-session.cookie.same-site=Lax
web-session.cookie.secure=true
#####################################################################################
# Web Client config
#####################################################################################
web-client.base-url=https://gcp.geneticscores.org
#####################################################################################
# Whitelist URIs
#####################################################################################
whitelist.paths=/pipeline-manager/integration/**,/key-handler/key/**,/user-manager/actuator/health,/pipeline-manager/actuator/health,/file-handler/actuator/health,/key-handler/actuator/health
